spring.application.name=chat

# === MySQL ===
spring.datasource.url=jdbc:mysql://localhost:3306/chat?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=Europe/Madrid
spring.datasource.username=root
spring.datasource.password=

# === JPA ===
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# === Servidor ===
server.port=8080

# === Spring Batch: inicializar schema (TEMPORAL) ===
spring.batch.job.enabled=false
spring.batch.jdbc.initialize-schema=NEVER
spring.sql.init.mode=never
spring.batch.jdbc.schema=classpath:org/springframework/batch/core/schema-mysql.sql
spring.sql.init.platform=mysql

# === Export CSV ===
app.exports.dir=C:/Users/PC/Desktop

# === Logs útiles ===
logging.level.org.springframework.batch=INFO
logging.level.com.chat.chat.Batch=INFO
