ALTER TABLE chats_grupales
    ADD COLUMN IF NOT EXISTS chat_cerrado TINYINT(1) NOT NULL DEFAULT 0,
    ADD COLUMN IF NOT EXISTS chat_cerrado_motivo VARCHAR(500) NULL,
    ADD COLUMN IF NOT EXISTS chat_cerrado_at TIMESTAMP NULL,
    ADD COLUMN IF NOT EXISTS chat_cerrado_by_admin_id BIGINT NULL,
    ADD COLUMN IF NOT EXISTS version BIGINT NOT NULL DEFAULT 0;
