package com.chat.chat.Service.SolicitudDesbaneoService;

import com.chat.chat.DTO.SolicitudDesbaneoCreateDTO;
import com.chat.chat.DTO.SolicitudDesbaneoCreateResponseDTO;
import com.chat.chat.DTO.SolicitudDesbaneoDTO;
import com.chat.chat.DTO.SolicitudDesbaneoEstadoUpdateDTO;
import com.chat.chat.DTO.SolicitudDesbaneoStatsDTO;
import com.chat.chat.DTO.SolicitudDesbaneoWsDTO;
import com.chat.chat.DTO.ChatCloseStateDTO;
import com.chat.chat.DTO.AiAppReportResolutionNoteInternalRequestDTO;
import com.chat.chat.DTO.AiAppReportResolutionNoteInternalResponseDTO;
import com.chat.chat.Entity.ChatGrupalEntity;
import com.chat.chat.Entity.SolicitudDesbaneoEntity;
import com.chat.chat.Entity.SolicitudReporteAdjuntoEntity;
import com.chat.chat.Entity.SolicitudReporteHistorialEntity;
import com.chat.chat.Entity.UsuarioEntity;
import com.chat.chat.Exceptions.ChatNoCerradoException;
import com.chat.chat.Exceptions.ConflictoException;
import com.chat.chat.Exceptions.RecursoNoEncontradoException;
import com.chat.chat.Mapper.SolicitudDesbaneoMapper;
import com.chat.chat.Repository.ChatGrupalRepository;
import com.chat.chat.Repository.SolicitudDesbaneoRepository;
import com.chat.chat.Repository.SolicitudReporteAdjuntoRepository;
import com.chat.chat.Repository.SolicitudReporteHistorialRepository;
import com.chat.chat.Repository.UsuarioRepository;
import com.chat.chat.Service.AiService.AiAppReportResolutionNoteMicroserviceClient;
import com.chat.chat.Service.ChatService.ChatService;
import com.chat.chat.Service.EmailService.EmailService;
import com.chat.chat.Service.UsuarioService.UsuarioService;
import com.chat.chat.Security.HttpRateLimitService;
import com.chat.chat.Utils.Constantes;
import com.chat.chat.Utils.ReporteTipo;
import com.chat.chat.Utils.SecurityUtils;
import com.chat.chat.Utils.SolicitudDesbaneoEstado;
import org.springframework.security.access.AccessDeniedException;
import jakarta.servlet.http.HttpServletRequest;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.core.io.ByteArrayResource;
import org.springframework.core.io.Resource;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageImpl;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.domain.Sort;
import org.springframework.http.HttpHeaders;
import org.springframework.http.MediaType;
import org.springframework.http.ResponseEntity;
import org.springframework.messaging.simp.SimpMessagingTemplate;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;
import org.springframework.web.context.request.RequestContextHolder;
import org.springframework.web.context.request.ServletRequestAttributes;

import java.time.LocalDateTime;
import java.time.ZoneId;
import java.time.ZonedDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashSet;
import java.util.List;
import java.util.Locale;
import java.util.Map;
import java.util.Objects;
import java.util.Optional;
import java.util.Set;
import java.util.UUID;
import java.util.regex.Pattern;
import java.util.stream.Collectors;

@Service
public class SolicitudDesbaneoServiceImpl implements SolicitudDesbaneoService {

    private static final Logger LOGGER = LoggerFactory.getLogger(SolicitudDesbaneoServiceImpl.class);
    private static final int MAX_REASON_LENGTH = 1000;
    private static final int DEFAULT_PAGE = 0;
    private static final int DEFAULT_SIZE = 20;
    private static final int MAX_SIZE = 100;
    private static final Pattern EMAIL_PATTERN = Pattern.compile("^[A-Za-z0-9._%+-]+@[A-Za-z0-9.-]+\\.[A-Za-z]{2,}$");
    private static final int MAX_AUTOGENERATED_REASON_LENGTH = 500;
    private static final String EVENT_CREATED = "UNBAN_APPEAL_CREATED";
    private static final String EVENT_UPDATED = "UNBAN_APPEAL_UPDATED";
    private static final String ACTION_CREACION = "CREACION";
    private static final String ACTION_CAMBIO_ESTADO = "CAMBIO_ESTADO";
    private static final int MAX_ATTACHMENT_FILE_NAME_LENGTH = 190;

    private final SolicitudDesbaneoRepository solicitudDesbaneoRepository;
    private final SolicitudReporteAdjuntoRepository solicitudReporteAdjuntoRepository;
    private final SolicitudReporteHistorialRepository solicitudReporteHistorialRepository;
    private final UsuarioRepository usuarioRepository;
    private final ChatGrupalRepository chatGrupalRepository;
    private final ChatService chatService;
    private final UsuarioService usuarioService;
    private final EmailService emailService;
    private final SecurityUtils securityUtils;
    private final SimpMessagingTemplate messagingTemplate;
    private final SolicitudDesbaneoMapper solicitudDesbaneoMapper;
    private final HttpRateLimitService httpRateLimitService;
    private final AiAppReportResolutionNoteMicroserviceClient aiAppReportResolutionNoteMicroserviceClient;

    public SolicitudDesbaneoServiceImpl(SolicitudDesbaneoRepository solicitudDesbaneoRepository,
                                        SolicitudReporteAdjuntoRepository solicitudReporteAdjuntoRepository,
                                        SolicitudReporteHistorialRepository solicitudReporteHistorialRepository,
                                        UsuarioRepository usuarioRepository,
                                        ChatGrupalRepository chatGrupalRepository,
                                        ChatService chatService,
                                        UsuarioService usuarioService,
                                        EmailService emailService,
                                        SecurityUtils securityUtils,
                                        SimpMessagingTemplate messagingTemplate,
                                        SolicitudDesbaneoMapper solicitudDesbaneoMapper,
                                        HttpRateLimitService httpRateLimitService,
                                        AiAppReportResolutionNoteMicroserviceClient aiAppReportResolutionNoteMicroserviceClient) {
        this.solicitudDesbaneoRepository = solicitudDesbaneoRepository;
        this.solicitudReporteAdjuntoRepository = solicitudReporteAdjuntoRepository;
        this.solicitudReporteHistorialRepository = solicitudReporteHistorialRepository;
        this.usuarioRepository = usuarioRepository;
        this.chatGrupalRepository = chatGrupalRepository;
        this.chatService = chatService;
        this.usuarioService = usuarioService;
        this.emailService = emailService;
        this.securityUtils = securityUtils;
        this.messagingTemplate = messagingTemplate;
        this.solicitudDesbaneoMapper = solicitudDesbaneoMapper;
        this.httpRateLimitService = httpRateLimitService;
        this.aiAppReportResolutionNoteMicroserviceClient = aiAppReportResolutionNoteMicroserviceClient;
    }

    @Override
    @Transactional
    public SolicitudDesbaneoCreateResponseDTO crearSolicitud(SolicitudDesbaneoCreateDTO request) {
        enforcePublicCreateRateLimit(request);
        if (request == null) {
            throw new IllegalArgumentException("Payload de solicitud de desbaneo vacio");
        }

        String email = normalizeAndValidateEmail(request.getEmail());
        String motivo = normalizeOptionalReason(request.getMotivo(), "motivo");

        UsuarioEntity usuario = usuarioRepository.findByEmail(email)
                .orElseThrow(() -> new RecursoNoEncontradoException(Constantes.MSG_SOLICITUD_DESBANEO_EMAIL_NO_EXISTE));

        if (usuario.isActivo()) {
            throw new ConflictoException(Constantes.MSG_SOLICITUD_DESBANEO_USUARIO_NO_BANEADO);
        }

        boolean alreadyOpen = solicitudDesbaneoRepository.existsByEmailAndEstadoIn(
                email,
                List.of(SolicitudDesbaneoEstado.PENDIENTE, SolicitudDesbaneoEstado.EN_REVISION));
        if (alreadyOpen) {
            throw new ConflictoException(Constantes.MSG_SOLICITUD_DESBANEO_YA_ABIERTA);
        }

        SolicitudDesbaneoEntity entity = new SolicitudDesbaneoEntity();
        entity.setTipoReporte(ReporteTipo.DESBANEO);
        entity.setUsuarioId(usuario.getId());
        entity.setEmail(email);
        entity.setMotivo(motivo);
        entity.setEstado(SolicitudDesbaneoEstado.PENDIENTE);

        SolicitudDesbaneoEntity saved = solicitudDesbaneoRepository.save(entity);

        LOGGER.info(Constantes.LOG_UNBAN_APPEAL_CREATED,
                saved.getId(),
                saved.getUsuarioId(),
                saved.getEmail(),
                saved.getEstado());
        registrarHistorialCreacion(saved);

        publishWsEvent(EVENT_CREATED, saved);
        return new SolicitudDesbaneoCreateResponseDTO(Constantes.MSG_SOLICITUD_DESBANEO_CREADA, saved.getId());
    }

    private void enforcePublicCreateRateLimit(SolicitudDesbaneoCreateDTO request) {
        HttpServletRequest httpRequest = currentHttpRequest();
        String email = request == null ? null : request.getEmail();
        httpRateLimitService.checkUnbanAppeal(httpRequest, email);
    }

    private HttpServletRequest currentHttpRequest() {
        var attrs = RequestContextHolder.getRequestAttributes();
        if (attrs instanceof ServletRequestAttributes servletRequestAttributes) {
            return servletRequestAttributes.getRequest();
        }
        return null;
    }

    @Override
    @Transactional
    public SolicitudDesbaneoDTO crearReporteChatCerrado(Long chatId, String motivo, String ip, String userAgent) {
        if (chatId == null) {
            throw new IllegalArgumentException("chatId es obligatorio");
        }
        Long usuarioId = securityUtils.getAuthenticatedUserId();
        UsuarioEntity usuario = usuarioRepository.findById(usuarioId)
                .orElseThrow(() -> new RecursoNoEncontradoException(Constantes.MSG_USUARIO_NO_ENCONTRADO));

        ChatGrupalEntity chat = chatGrupalRepository.findByIdWithUsuarios(chatId)
                .orElseThrow(() -> new RecursoNoEncontradoException(Constantes.MSG_CHAT_GRUPAL_NO_ENCONTRADO_ID + chatId));
        if (!chat.isActivo()) {
            throw new RecursoNoEncontradoException(Constantes.MSG_CHAT_GRUPAL_NO_ENCONTRADO_ID + chatId);
        }
        boolean esMiembro = chat.getUsuarios() != null && chat.getUsuarios().stream()
                .filter(Objects::nonNull)
                .anyMatch(u -> Objects.equals(u.getId(), usuarioId) && u.isActivo());
        if (!esMiembro) {
            throw new AccessDeniedException(Constantes.MSG_NO_PERTENECE_GRUPO);
        }
        boolean chatCerrado = chat.isClosed() || chat.getClosedAt() != null;
        if (!chatCerrado) {
            throw new ChatNoCerradoException(Constantes.MSG_CHAT_GRUPAL_NO_CERRADO);
        }

        boolean duplicateOpen = solicitudDesbaneoRepository.existsByTipoReporteAndUsuarioIdAndChatIdAndEstadoIn(
                ReporteTipo.CHAT_CERRADO,
                usuarioId,
                chatId,
                List.of(SolicitudDesbaneoEstado.PENDIENTE, SolicitudDesbaneoEstado.EN_REVISION));
        if (duplicateOpen) {
            throw new ConflictoException(Constantes.MSG_REPORTE_CHAT_CERRADO_DUPLICADO);
        }

        SolicitudDesbaneoEntity entity = new SolicitudDesbaneoEntity();
        entity.setTipoReporte(ReporteTipo.CHAT_CERRADO);
        entity.setUsuarioId(usuarioId);
        entity.setEmail(usuario.getEmail());
        entity.setChatId(chatId);
        entity.setChatNombreSnapshot(trimToNullable(chat.getNombreGrupo(), 190));
        entity.setChatCerradoMotivoSnapshot(trimToNullable(chat.getClosedReason(), 500));
        entity.setMotivo(normalizeOptionalReason(motivo, "motivo", 500));
        entity.setEstado(SolicitudDesbaneoEstado.PENDIENTE);

        SolicitudDesbaneoEntity saved = solicitudDesbaneoRepository.save(entity);
        LOGGER.info("[CHAT_CLOSED_REPORT_CREATED] id={} usuarioId={} chatId={} estado={} ip={} userAgent={} chatClosedReasonSnapshot={}",
                saved.getId(),
                saved.getUsuarioId(),
                saved.getChatId(),
                saved.getEstado(),
                safeAuditValue(ip),
                safeAuditValue(userAgent),
                safeAuditValue(saved.getChatCerradoMotivoSnapshot()));
        registrarHistorialCreacion(saved);
        publishWsEvent(EVENT_CREATED, saved);
        return solicitudDesbaneoMapper.toDto(saved, usuario);
    }

    @Override
    @Transactional
    public SolicitudDesbaneoDTO crearReporteDesdeAi(Long usuarioId, ReporteTipo tipo, String motivo) {
        return crearReporteDesdeAi(usuarioId, tipo, motivo, null, null, null);
    }

    @Override
    @Transactional
    public SolicitudDesbaneoDTO crearReporteDesdeAi(Long usuarioId, ReporteTipo tipo, String motivo,
                                                    String imagenMimeType, String imagenNombreArchivo, byte[] imagenContenido) {
        if (usuarioId == null) {
            throw new IllegalArgumentException("usuarioId es obligatorio");
        }
        if (tipo == null) {
            tipo = ReporteTipo.OTRO;
        }
        // Block CHAT_CERRADO/DESBANEO via AI fork to keep flows separated
        if (tipo == ReporteTipo.CHAT_CERRADO) {
            throw new IllegalArgumentException("CHAT_CERRADO no se permite via AI");
        }
        UsuarioEntity usuario = usuarioRepository.findById(usuarioId)
                .orElseThrow(() -> new RecursoNoEncontradoException(Constantes.MSG_USUARIO_NO_ENCONTRADO));

        // Trust user email from auth, never client
        String email = usuario.getEmail();
        String motivoSanitized = normalizeOptionalReason(motivo, "motivo");

        SolicitudDesbaneoEntity entity = new SolicitudDesbaneoEntity();
        entity.setTipoReporte(tipo);
        entity.setUsuarioId(usuarioId);
        entity.setEmail(email);
        entity.setMotivo(motivoSanitized);
        entity.setEstado(SolicitudDesbaneoEstado.PENDIENTE);

        SolicitudDesbaneoEntity saved = solicitudDesbaneoRepository.save(entity);
        saveImageAttachmentIfPresent(saved.getId(), imagenMimeType, imagenNombreArchivo, imagenContenido);
        LOGGER.info("[APP_REPORT_CREATED] id={} usuarioId={} tipoReporte={} estado={} motivoLength={}",
                saved.getId(),
                saved.getUsuarioId(),
                saved.getTipoReporte(),
                saved.getEstado(),
                motivoSanitized == null ? 0 : motivoSanitized.length());
        registrarHistorialCreacion(saved);
        publishWsEvent(EVENT_CREATED, saved);
        return solicitudDesbaneoMapper.toDto(saved, usuario);
    }

    @Override
    public Page<SolicitudDesbaneoDTO> listarSolicitudes(String estado, String estados, String tipoReporte, Integer page, Integer size, String sort) {
        int safePage = page == null ? DEFAULT_PAGE : Math.max(DEFAULT_PAGE, page);
        int requestedSize = size == null ? DEFAULT_SIZE : size;
        int safeSize = Math.max(1, Math.min(MAX_SIZE, requestedSize));

        Pageable pageable = PageRequest.of(safePage, safeSize, resolveSort(sort));
        List<SolicitudDesbaneoEstado> estadoFilters = parseEstadosFilter(estado, estados);
        ReporteTipo tipo = parseTipoReporteFilter(tipoReporte);
        Page<SolicitudDesbaneoEntity> resultPage = resolveListadoByFilters(estadoFilters, tipo, pageable);
        Map<Long, UsuarioEntity> usuariosById = loadUsuariosById(resultPage.getContent());
        Map<Long, SolicitudReporteAdjuntoEntity> adjuntosBySolicitudId = loadAdjuntosBySolicitudId(resultPage.getContent());
        List<SolicitudDesbaneoDTO> content = resultPage.getContent().stream()
                .map(entity -> enrichSolicitudDto(
                        solicitudDesbaneoMapper.toDto(entity, entity.getUsuarioId() == null ? null : usuariosById.get(entity.getUsuarioId())),
                        adjuntosBySolicitudId.get(entity.getId()),
                        true))
                .collect(Collectors.toList());
        return new PageImpl<>(content, pageable, resultPage.getTotalElements());
    }

    @Override
    public SolicitudDesbaneoDTO obtenerSolicitud(Long id) {
        SolicitudDesbaneoEntity entity = solicitudDesbaneoRepository.findById(id)
                .orElseThrow(() -> new RecursoNoEncontradoException(Constantes.MSG_SOLICITUD_DESBANEO_NO_ENCONTRADA));
        Map<Long, UsuarioEntity> usuariosById = loadUsuariosById(List.of(entity));
        SolicitudReporteAdjuntoEntity adjunto = solicitudReporteAdjuntoRepository.findBySolicitudId(entity.getId()).orElse(null);
        return enrichSolicitudDto(solicitudDesbaneoMapper.toDto(entity, usuariosById.get(entity.getUsuarioId())), adjunto, true);
    }

    @Override
    @Transactional
    public SolicitudDesbaneoDTO actualizarEstado(Long id, SolicitudDesbaneoEstadoUpdateDTO request, HttpServletRequest httpRequest) {
        if (request == null || request.getEstado() == null || request.getEstado().isBlank()) {
            throw new IllegalArgumentException("estado es obligatorio");
        }

        SolicitudDesbaneoEntity entity = solicitudDesbaneoRepository.findById(id)
                .orElseThrow(() -> new RecursoNoEncontradoException(Constantes.MSG_SOLICITUD_DESBANEO_NO_ENCONTRADA));
        SolicitudDesbaneoEstado newEstado = parseEstadoRequired(request.getEstado());
        SolicitudDesbaneoEstado oldEstado = entity.getEstado();
        Long reviewedByAdminId = securityUtils.getAuthenticatedUserId();
        boolean resolucionRequestEmpty = isBlank(request.getResolucionMotivo());
        boolean resolucionActualEmpty = isBlank(entity.getResolucionMotivo());
        String requestId = resolveRequestId(httpRequest);

        LOGGER.info("[ADMIN][REPORT_STATUS] requestId={} solicitudId={} fromEstado={} toEstado={} resolucionRequestEmpty={}",
                requestId, entity.getId(), oldEstado, newEstado, resolucionRequestEmpty);

        String resolucionMotivo = normalizeOptionalReason(request.getResolucionMotivo(), "resolucionMotivo", MAX_REASON_LENGTH);
        boolean resolucionAutogenerada = false;
        if (shouldAutogenerateResolution(newEstado, request.getResolucionMotivo(), entity.getResolucionMotivo())) {
            try {
                resolucionMotivo = generateAutomaticResolution(requestId, entity, newEstado);
                resolucionAutogenerada = hasText(resolucionMotivo);
                if (!resolucionAutogenerada) {
                    resolucionMotivo = buildFallbackResolution(entity.getTipoReporte(), newEstado);
                    LOGGER.warn("[ADMIN][REPORT_STATUS] requestId={} solicitudId={} resolucionAutogenerada=false fallback=true error=empty-resolution",
                            requestId, entity.getId());
                }
                LOGGER.info("[ADMIN][REPORT_STATUS] requestId={} solicitudId={} estado={} resolucionAutogenerada={} resolucionLength={}",
                        requestId, entity.getId(), newEstado, resolucionAutogenerada,
                        resolucionMotivo == null ? 0 : resolucionMotivo.length());
            } catch (RuntimeException ex) {
                resolucionMotivo = buildFallbackResolution(entity.getTipoReporte(), newEstado);
                LOGGER.warn("[ADMIN][REPORT_STATUS] requestId={} solicitudId={} resolucionAutogenerada=false fallback=true error={}",
                        requestId, entity.getId(), safeAuditValue(ex.getMessage()));
            }
        }

        entity.setEstado(newEstado);
        entity.setReviewedByAdminId(reviewedByAdminId);
        entity.setResolucionMotivo(resolucionMotivo);

        UsuarioEntity usuario = resolveUsuario(entity);
        String ip = resolveRequestIp(httpRequest);
        String userAgent = resolveRequestUserAgent(httpRequest);
        boolean alreadyApproved = oldEstado == SolicitudDesbaneoEstado.APROBADA;
        boolean userAlreadyActive = usuario != null && usuario.isActivo();

        if (newEstado == SolicitudDesbaneoEstado.RECHAZADA && entity.getTipoReporte() == ReporteTipo.CHAT_CERRADO) {
            boolean alreadyRejected = oldEstado == SolicitudDesbaneoEstado.RECHAZADA;
            if (!alreadyRejected) {
                sendChatReopenRejectedEmail(entity, resolucionMotivo);
            }
        }

        if (newEstado == SolicitudDesbaneoEstado.APROBADA && entity.getTipoReporte() == ReporteTipo.CHAT_CERRADO) {
            handleChatClosedReportApproval(entity, resolucionMotivo, ip, userAgent);
        }

        if (newEstado == SolicitudDesbaneoEstado.APROBADA) {
            // Reutiliza exactamente la lógica administrativa existente para desbanear.
            if (entity.getTipoReporte() != ReporteTipo.CHAT_CERRADO && !alreadyApproved && !userAlreadyActive) {
                usuarioService.desbanearAdministrativamente(usuario.getId(), resolucionMotivo);
            }
        } else if (newEstado == SolicitudDesbaneoEstado.RECHAZADA && entity.getTipoReporte() != ReporteTipo.CHAT_CERRADO) {
            boolean alreadyRejected = oldEstado == SolicitudDesbaneoEstado.RECHAZADA;
            if (!alreadyRejected) {
                sendRejectionEmail(usuario, entity.getEmail(), resolucionMotivo);
            }
        }

        SolicitudDesbaneoEntity saved = solicitudDesbaneoRepository.save(entity);
        registrarHistorialCambioEstado(requestId, saved, oldEstado, newEstado, reviewedByAdminId, resolucionMotivo);
        LOGGER.info(Constantes.LOG_UNBAN_APPEAL_STATUS_UPDATED,
                saved.getId(),
                oldEstado,
                saved.getEstado(),
                reviewedByAdminId,
                LocalDateTime.now());

        publishWsEvent(EVENT_UPDATED, saved);
        Map<Long, UsuarioEntity> usuariosById = loadUsuariosById(List.of(saved));
        SolicitudReporteAdjuntoEntity adjunto = solicitudReporteAdjuntoRepository.findBySolicitudId(saved.getId()).orElse(null);
        return enrichSolicitudDto(solicitudDesbaneoMapper.toDto(saved, usuariosById.get(saved.getUsuarioId())), adjunto, true);
    }

    @Override
    @Transactional(readOnly = true)
    public ResponseEntity<Resource> obtenerImagenReporteAdmin(Long id) {
        SolicitudDesbaneoEntity solicitud = solicitudDesbaneoRepository.findById(id)
                .orElseThrow(() -> new RecursoNoEncontradoException(Constantes.MSG_SOLICITUD_DESBANEO_NO_ENCONTRADA));
        SolicitudReporteAdjuntoEntity adjunto = solicitudReporteAdjuntoRepository.findBySolicitudId(solicitud.getId())
                .orElseThrow(() -> new RecursoNoEncontradoException("La solicitud no tiene imagen adjunta"));
        return buildAttachmentResponse(adjunto);
    }

    @Override
    @Transactional(readOnly = true)
    public ResponseEntity<Resource> obtenerImagenReporteUsuario(Long id) {
        SolicitudDesbaneoEntity solicitud = solicitudDesbaneoRepository.findById(id)
                .orElseThrow(() -> new RecursoNoEncontradoException(Constantes.MSG_SOLICITUD_DESBANEO_NO_ENCONTRADA));
        Long authUserId = securityUtils.getAuthenticatedUserId();
        boolean admin = securityUtils.hasRole(Constantes.ADMIN) || securityUtils.hasRole(Constantes.ROLE_ADMIN);
        if (!admin && !Objects.equals(solicitud.getUsuarioId(), authUserId)) {
            throw new AccessDeniedException("No puedes acceder a la imagen de otro usuario");
        }
        SolicitudReporteAdjuntoEntity adjunto = solicitudReporteAdjuntoRepository.findBySolicitudId(solicitud.getId())
                .orElseThrow(() -> new RecursoNoEncontradoException("La solicitud no tiene imagen adjunta"));
        return buildAttachmentResponse(adjunto);
    }

    @Override
    public SolicitudDesbaneoStatsDTO obtenerStats() {
        return obtenerStats(null);
    }

    @Override
    public SolicitudDesbaneoStatsDTO obtenerStats(String tz) {
        long pendientes = solicitudDesbaneoRepository.countByEstado(SolicitudDesbaneoEstado.PENDIENTE);
        long enRevision = solicitudDesbaneoRepository.countByEstado(SolicitudDesbaneoEstado.EN_REVISION);
        long aprobadas = solicitudDesbaneoRepository.countByEstado(SolicitudDesbaneoEstado.APROBADA);
        long rechazadas = solicitudDesbaneoRepository.countByEstado(SolicitudDesbaneoEstado.RECHAZADA);
        ZoneId queryZone = resolveZoneId(tz);
        ZoneId serverZone = ZoneId.systemDefault();
        ZonedDateTime nowInQueryZone = ZonedDateTime.now(queryZone);
        ZonedDateTime startOfDayInQueryZone = nowInQueryZone.toLocalDate().atStartOfDay(queryZone);
        ZonedDateTime endOfDayInQueryZone = startOfDayInQueryZone.plusDays(1);

        LocalDateTime from = startOfDayInQueryZone.withZoneSameInstant(serverZone).toLocalDateTime();
        LocalDateTime to = endOfDayInQueryZone.withZoneSameInstant(serverZone).toLocalDateTime();
        List<SolicitudDesbaneoEntity> todayRows = solicitudDesbaneoRepository
                .findByCreatedAtGreaterThanEqualAndCreatedAtLessThan(from, to);

        Set<String> uniqueReporters = new HashSet<>();
        for (SolicitudDesbaneoEntity row : todayRows) {
            if (row == null) {
                continue;
            }
            if (row.getUsuarioId() != null) {
                uniqueReporters.add("u:" + row.getUsuarioId());
                continue;
            }
            String normalizedEmail = normalizeEmailNullable(row.getEmail());
            if (normalizedEmail != null) {
                uniqueReporters.add("e:" + normalizedEmail);
            }
        }

        SolicitudDesbaneoStatsDTO stats = new SolicitudDesbaneoStatsDTO();
        stats.setPendientes(pendientes);
        stats.setEnRevision(enRevision);
        stats.setAprobadas(aprobadas);
        stats.setRechazadas(rechazadas);
        stats.setAbiertas(pendientes + enRevision);
        stats.setHoyReportantesUnicos(uniqueReporters.size());
        stats.setFechaReferencia(nowInQueryZone.toLocalDate().toString());
        stats.setTimezone(queryZone.getId());
        return stats;
    }

    private void publishWsEvent(String eventName, SolicitudDesbaneoEntity entity) {
        UsuarioEntity usuario = entity.getUsuarioId() == null
                ? null
                : usuarioRepository.findById(entity.getUsuarioId()).orElse(null);
        SolicitudDesbaneoWsDTO payload = solicitudDesbaneoMapper.toWsDto(eventName, entity, usuario);
        messagingTemplate.convertAndSend(Constantes.TOPIC_ADMIN_SOLICITUDES_DESBANEO, payload);
    }

    private Page<SolicitudDesbaneoEntity> resolveListadoByFilters(List<SolicitudDesbaneoEstado> estadoFilters,
                                                                   ReporteTipo tipoReporte,
                                                                   Pageable pageable) {
        boolean hasEstados = estadoFilters != null && !estadoFilters.isEmpty();
        if (tipoReporte == null) {
            return hasEstados
                    ? solicitudDesbaneoRepository.findAllByEstadoIn(estadoFilters, pageable)
                    : solicitudDesbaneoRepository.findAll(pageable);
        }
        return hasEstados
                ? solicitudDesbaneoRepository.findAllByTipoReporteAndEstadoIn(tipoReporte, estadoFilters, pageable)
                : solicitudDesbaneoRepository.findAllByTipoReporte(tipoReporte, pageable);
    }

    private Map<Long, UsuarioEntity> loadUsuariosById(List<SolicitudDesbaneoEntity> solicitudes) {
        if (solicitudes == null || solicitudes.isEmpty()) {
            return Map.of();
        }
        Set<Long> ids = solicitudes.stream()
                .map(SolicitudDesbaneoEntity::getUsuarioId)
                .filter(Objects::nonNull)
                .collect(Collectors.toSet());
        if (ids.isEmpty()) {
            return Map.of();
        }
        Map<Long, UsuarioEntity> out = new HashMap<>();
        usuarioRepository.findAllById(ids).forEach(usuario -> out.put(usuario.getId(), usuario));
        return out;
    }

    private Map<Long, SolicitudReporteAdjuntoEntity> loadAdjuntosBySolicitudId(List<SolicitudDesbaneoEntity> solicitudes) {
        if (solicitudes == null || solicitudes.isEmpty()) {
            return Map.of();
        }
        Set<Long> ids = solicitudes.stream()
                .map(SolicitudDesbaneoEntity::getId)
                .filter(Objects::nonNull)
                .collect(Collectors.toSet());
        if (ids.isEmpty()) {
            return Map.of();
        }
        return solicitudReporteAdjuntoRepository.findBySolicitudIdIn(ids).stream()
                .filter(Objects::nonNull)
                .collect(Collectors.toMap(SolicitudReporteAdjuntoEntity::getSolicitudId, adjunto -> adjunto, (a, b) -> a));
    }

    private SolicitudDesbaneoDTO enrichSolicitudDto(SolicitudDesbaneoDTO dto,
                                                    SolicitudReporteAdjuntoEntity adjunto,
                                                    boolean adminUrl) {
        if (dto == null) {
            return null;
        }
        if (adjunto == null) {
            dto.setTieneImagenReporte(Boolean.FALSE);
            return dto;
        }
        dto.setTieneImagenReporte(Boolean.TRUE);
        dto.setImagenReporteMimeType(adjunto.getMimeType());
        dto.setImagenReporteNombre(adjunto.getNombreArchivo());
        dto.setImagenReporteSize(adjunto.getSizeBytes());
        dto.setImagenReporteUrl(buildAttachmentUrl(dto.getId(), adminUrl));
        return dto;
    }

    private void saveImageAttachmentIfPresent(Long solicitudId,
                                              String imagenMimeType,
                                              String imagenNombreArchivo,
                                              byte[] imagenContenido) {
        if (solicitudId == null || imagenContenido == null || imagenContenido.length == 0) {
            return;
        }
        SolicitudReporteAdjuntoEntity adjunto = new SolicitudReporteAdjuntoEntity();
        adjunto.setSolicitudId(solicitudId);
        adjunto.setMimeType(trimToNullable(imagenMimeType, 100));
        adjunto.setNombreArchivo(sanitizeAttachmentFileName(imagenNombreArchivo));
        adjunto.setSizeBytes((long) imagenContenido.length);
        adjunto.setContenido(imagenContenido);
        solicitudReporteAdjuntoRepository.save(adjunto);
    }

    private String sanitizeAttachmentFileName(String nombreArchivo) {
        String safe = trimToNullable(nombreArchivo, MAX_ATTACHMENT_FILE_NAME_LENGTH);
        if (!hasText(safe)) {
            return "reporte-app";
        }
        safe = safe.replace('\\', '_').replace('/', '_');
        safe = safe.replaceAll("[\\r\\n\\t\\x00-\\x1F\\x7F]+", "_");
        safe = safe.replaceAll("[^A-Za-z0-9._ -]", "_");
        safe = safe.trim();
        if (safe.isBlank()) {
            return "reporte-app";
        }
        return safe.length() > MAX_ATTACHMENT_FILE_NAME_LENGTH
                ? safe.substring(0, MAX_ATTACHMENT_FILE_NAME_LENGTH)
                : safe;
    }

    private String buildAttachmentUrl(Long solicitudId, boolean adminUrl) {
        if (solicitudId == null) {
            return null;
        }
        String template = adminUrl
                ? Constantes.USUARIO_API + Constantes.ADMIN_SOLICITUD_DESBANEO_IMAGEN
                : Constantes.USUARIO_API + Constantes.SOLICITUD_DESBANEO_IMAGEN_USUARIO;
        return template.replace("{id}", String.valueOf(solicitudId));
    }

    private ResponseEntity<Resource> buildAttachmentResponse(SolicitudReporteAdjuntoEntity adjunto) {
        byte[] content = Optional.ofNullable(adjunto.getContenido()).orElseGet(() -> new byte[0]);
        String fileName = sanitizeAttachmentFileName(adjunto.getNombreArchivo());
        String mimeType = hasText(adjunto.getMimeType()) ? adjunto.getMimeType() : MediaType.APPLICATION_OCTET_STREAM_VALUE;
        return ResponseEntity.ok()
                .header(HttpHeaders.CONTENT_DISPOSITION, "inline; filename=\"" + fileName + "\"")
                .header("X-Content-Type-Options", "nosniff")
                .contentType(MediaType.parseMediaType(mimeType))
                .contentLength(content.length)
                .body(new ByteArrayResource(content));
    }

    private boolean shouldAutogenerateResolution(SolicitudDesbaneoEstado estado,
                                                 String resolucionRequest,
                                                 String resolucionActual) {
        return (estado == SolicitudDesbaneoEstado.EN_REVISION
                || estado == SolicitudDesbaneoEstado.APROBADA
                || estado == SolicitudDesbaneoEstado.RECHAZADA)
                && isBlank(resolucionRequest)
                && isBlank(resolucionActual);
    }

    private String generateAutomaticResolution(String requestId,
                                               SolicitudDesbaneoEntity entity,
                                               SolicitudDesbaneoEstado estadoDestino) {
        AiAppReportResolutionNoteInternalRequestDTO request = new AiAppReportResolutionNoteInternalRequestDTO();
        request.setRequestId(requestId);
        request.setTipoReporte(entity.getTipoReporte() == null ? null : entity.getTipoReporte().name());
        request.setEstadoDestino(estadoDestino == null ? null : estadoDestino.name());
        request.setMotivo(trimToNullable(entity.getMotivo(), MAX_REASON_LENGTH));
        request.setResolucionAdmin(trimToNullable(entity.getResolucionMotivo(), MAX_REASON_LENGTH));
        request.setUsuarioNombre(resolveReportUserName(entity));
        request.setCreatedAt(entity.getCreatedAt() == null ? null : entity.getCreatedAt().toString());

        AiAppReportResolutionNoteInternalResponseDTO response =
                aiAppReportResolutionNoteMicroserviceClient.generateResolutionNote(requestId, request);
        if (response == null || !response.isSuccess()) {
            throw new IllegalStateException(response == null ? "null-response" : response.getCodigo());
        }

        String resolucion = normalizeOptionalReason(
                trimToNullable(response.getResolucionMotivo(), MAX_AUTOGENERATED_REASON_LENGTH),
                "resolucionMotivo",
                MAX_REASON_LENGTH);
        if (!hasText(resolucion)) {
            throw new IllegalStateException("empty-resolution");
        }
        return resolucion;
    }

    private String resolveReportUserName(SolicitudDesbaneoEntity entity) {
        UsuarioEntity usuario = null;
        if (entity != null && entity.getUsuarioId() != null) {
            usuario = usuarioRepository.findById(entity.getUsuarioId()).orElse(null);
        }
        if (usuario != null && hasText(usuario.getNombre())) {
            return trimToNullable(usuario.getNombre(), 120);
        }
        return null;
    }

    private String buildFallbackResolution(ReporteTipo tipoReporte, SolicitudDesbaneoEstado estadoDestino) {
        ReporteTipo tipo = tipoReporte == null ? ReporteTipo.OTRO : tipoReporte;
        if (estadoDestino == null) {
            return "Reporte revisado por administracion.";
        }
        return switch (estadoDestino) {
            case PENDIENTE -> "Este reporte sigue pendiente de revision. Administracion todavia no ha empezado a revisarlo.";
            case EN_REVISION -> switch (tipo) {
                case ERROR_APP -> "Error de aplicacion en revision: administracion revisara el caso para localizar la causa.";
                case INCIDENCIA -> "Incidencia en revision: pendiente de validacion tecnica por administracion.";
                case MEJORA -> "Mejora en revision: administracion esta valorando la propuesta indicada por el usuario.";
                case QUEJA -> "Queja en revision: administracion esta revisando la situacion indicada por el usuario.";
                case SUGERENCIA -> "Sugerencia en revision: administracion esta valorando la propuesta enviada por el usuario.";
                case DESBANEO -> "Solicitud de desbaneo en revision: administracion esta revisando la peticion del usuario.";
                case CHAT_CERRADO -> "Solicitud de reapertura de chat en revision: administracion esta revisando el caso.";
                default -> "Reporte en revision: pendiente de analisis por administracion.";
            };
            case APROBADA -> switch (tipo) {
                case ERROR_APP -> "Error de aplicacion resuelto: administracion ha revisado el problema reportado y lo marca como solucionado.";
                case INCIDENCIA -> "Incidencia resuelta: administracion ha revisado el problema indicado y lo marca como solucionado.";
                case MEJORA -> "Mejora revisada: administracion ha valorado positivamente la propuesta y la deja registrada como aceptada o revisada.";
                case QUEJA -> "Queja atendida: administracion ha revisado la queja y la marca como atendida.";
                case SUGERENCIA -> "Sugerencia revisada: administracion ha revisado la propuesta y la deja registrada como valorada.";
                case DESBANEO -> "Solicitud de desbaneo aprobada: administracion ha aprobado la solicitud.";
                case CHAT_CERRADO -> "Solicitud de reapertura aprobada: administracion ha aprobado la reapertura del chat.";
                default -> "Reporte revisado favorablemente: administracion ha aprobado o atendido el caso.";
            };
            case RECHAZADA -> switch (tipo) {
                case ERROR_APP -> "Error de aplicacion descartado: administracion ha revisado el reporte y no aplicara cambios por ahora.";
                case INCIDENCIA -> "Incidencia descartada: administracion ha revisado el caso y no aplicara cambios por ahora.";
                case MEJORA -> "Mejora descartada: administracion ha revisado la propuesta y no la aplicara por ahora.";
                case QUEJA -> "Queja descartada: administracion ha revisado la queja y no aplicara acciones adicionales por ahora.";
                case SUGERENCIA -> "Sugerencia descartada: administracion ha revisado la propuesta y no la aplicara por ahora.";
                case DESBANEO -> "Solicitud de desbaneo rechazada: administracion ha revisado la peticion y no la aprueba por ahora.";
                case CHAT_CERRADO -> "Solicitud de reapertura rechazada: administracion ha revisado el caso y no reabrira el chat por ahora.";
                default -> "Reporte descartado: administracion ha revisado el caso y no aplicara cambios por ahora.";
            };
        };
    }

    private String resolveRequestId(HttpServletRequest request) {
        if (request != null) {
            String requestId = trimToNullable(request.getHeader("X-Request-Id"), 120);
            if (requestId != null) {
                return requestId;
            }
            String traceId = trimToNullable(request.getHeader("X-Trace-Id"), 120);
            if (traceId != null) {
                return traceId;
            }
        }
        return UUID.randomUUID().toString();
    }

    private UsuarioEntity resolveUsuario(SolicitudDesbaneoEntity entity) {
        if (entity == null) {
            throw new RecursoNoEncontradoException(Constantes.MSG_SOLICITUD_DESBANEO_NO_ENCONTRADA);
        }
        UsuarioEntity usuario = null;
        if (entity.getUsuarioId() != null) {
            usuario = usuarioRepository.findById(entity.getUsuarioId()).orElse(null);
        }
        if (usuario == null && entity.getEmail() != null && !entity.getEmail().isBlank()) {
            usuario = usuarioRepository.findByEmail(entity.getEmail()).orElse(null);
        }
        if (usuario == null) {
            throw new RecursoNoEncontradoException(Constantes.MSG_USUARIO_NO_ENCONTRADO);
        }
        return usuario;
    }

    private void sendRejectionEmail(UsuarioEntity usuario, String emailFallback, String resolucionMotivo) {
        if (usuario == null && (emailFallback == null || emailFallback.isBlank())) {
            return;
        }
        String email = usuario != null && usuario.getEmail() != null && !usuario.getEmail().isBlank()
                ? usuario.getEmail()
                : emailFallback;
        String nombre = usuario != null && usuario.getNombre() != null && !usuario.getNombre().isBlank()
                ? usuario.getNombre()
                : "Usuario";
        Map<String, String> vars = new HashMap<>();
        vars.put(Constantes.EMAIL_VAR_NOMBRE, safeEmailValue(nombre));
        vars.put(Constantes.EMAIL_VAR_MOTIVO, safeEmailValue(resolucionMotivo == null ? Constantes.MSG_SOLICITUD_DESBANEO_RECHAZADA_DEFAULT : resolucionMotivo));

        emailService.sendHtmlEmail(
                email,
                Constantes.EMAIL_SUBJECT_UNBAN_REJECTED,
                Constantes.EMAIL_TEMPLATE_UNBAN_REJECTED,
                vars
        );
    }

    private void sendChatReopenRejectedEmail(SolicitudDesbaneoEntity entity, String resolucionMotivo) {
        if (entity == null || entity.getEmail() == null || entity.getEmail().isBlank()) {
            return;
        }
        Map<String, String> vars = new HashMap<>();
        vars.put(Constantes.EMAIL_VAR_NOMBRE, safeEmailValue("Usuario"));
        vars.put("nombreGrupo", safeEmailValue(defaultString(entity.getChatNombreSnapshot(), "el grupo")));
        vars.put("chatId", safeEmailValue(entity.getChatId() == null ? "-" : String.valueOf(entity.getChatId())));
        vars.put("motivoCierre", safeEmailValue(defaultString(entity.getChatCerradoMotivoSnapshot(), "No disponible")));
        vars.put("resolucionMotivo", safeEmailValue(defaultString(resolucionMotivo, Constantes.MSG_SOLICITUD_DESBANEO_RECHAZADA_DEFAULT)));

        emailService.sendHtmlEmail(
                entity.getEmail(),
                buildChatReopenSubject(false, entity.getChatNombreSnapshot()),
                Constantes.EMAIL_TEMPLATE_CHAT_REOPEN_REJECTED,
                vars
        );
    }

    private void handleChatClosedReportApproval(SolicitudDesbaneoEntity entity, String resolucionMotivo, String ip, String userAgent) {
        if (entity == null || entity.getChatId() == null) {
            throw new IllegalArgumentException("chatId es obligatorio para solicitudes CHAT_CERRADO");
        }
        ChatCloseStateDTO state = chatService.reabrirChatGrupalComoAdmin(entity.getChatId(), ip, userAgent);
        LOGGER.info("[AUDIT_CHAT_CLOSED_REPORT_RESOLVED] action=APPROVE adminId={} solicitudId={} chatId={} ip={} userAgent={} resolucionMotivo={} chatClosedState={}",
                securityUtils.getAuthenticatedUserId(),
                entity.getId(),
                entity.getChatId(),
                safeAuditValue(ip),
                safeAuditValue(userAgent),
                safeAuditValue(resolucionMotivo),
                state == null ? "-" : String.valueOf(state.isClosed()));

        if (entity.getEmail() == null || entity.getEmail().isBlank()) {
            return;
        }
        Map<String, String> vars = new HashMap<>();
        vars.put(Constantes.EMAIL_VAR_NOMBRE, safeEmailValue("Usuario"));
        vars.put("nombreGrupo", safeEmailValue(defaultString(entity.getChatNombreSnapshot(), "el grupo")));
        vars.put("chatId", safeEmailValue(String.valueOf(entity.getChatId())));
        vars.put("motivoCierre", safeEmailValue(defaultString(entity.getChatCerradoMotivoSnapshot(), "No disponible")));
        vars.put("resolucionMotivo", safeEmailValue(defaultString(resolucionMotivo, Constantes.MSG_SOLICITUD_DESBANEO_APROBADA_DEFAULT)));
        vars.put("fecha", safeEmailValue(LocalDateTime.now().toString()));

        emailService.sendHtmlEmail(
                entity.getEmail(),
                buildChatReopenSubject(true, entity.getChatNombreSnapshot()),
                Constantes.EMAIL_TEMPLATE_CHAT_REOPEN_APPROVED,
                vars
        );
    }

    private Sort resolveSort(String sortRaw) {
        if (sortRaw == null || sortRaw.isBlank()) {
            return Sort.by(Sort.Order.desc("createdAt"), Sort.Order.desc("id"));
        }
        String[] parts = sortRaw.trim().split(",", 2);
        String field = parts[0].trim();
        if (field.isBlank()) {
            field = "createdAt";
        }

        Set<String> allowed = Set.of("createdAt", "updatedAt", "estado", "email", "id", "usuarioId", "tipoReporte", "chatId");
        if (!allowed.contains(field)) {
            field = "createdAt";
        }

        String dirRaw = parts.length > 1 ? parts[1].trim().toLowerCase(Locale.ROOT) : "desc";
        Sort.Direction direction = "asc".equals(dirRaw) ? Sort.Direction.ASC : Sort.Direction.DESC;
        Sort sort = Sort.by(new Sort.Order(direction, field));
        if (!"id".equals(field)) {
            sort = sort.and(Sort.by(Sort.Order.desc("id")));
        }
        return sort;
    }

    private String normalizeAndValidateEmail(String emailRaw) {
        if (emailRaw == null || emailRaw.isBlank()) {
            throw new IllegalArgumentException("email es obligatorio");
        }
        String normalized = emailRaw.trim().toLowerCase(Locale.ROOT);
        if (normalized.length() > 190 || !EMAIL_PATTERN.matcher(normalized).matches()) {
            throw new IllegalArgumentException("email invalido");
        }
        return normalized;
    }

    private String normalizeEmailNullable(String emailRaw) {
        if (emailRaw == null) {
            return null;
        }
        String normalized = emailRaw.trim().toLowerCase(Locale.ROOT);
        return normalized.isBlank() ? null : normalized;
    }

    private ReporteTipo parseTipoReporteFilter(String raw) {
        if (raw == null || raw.isBlank()) {
            return null;
        }
        try {
            return ReporteTipo.valueOf(raw.trim().toUpperCase(Locale.ROOT));
        } catch (IllegalArgumentException ex) {
            throw new IllegalArgumentException("tipoReporte invalido. Valores permitidos: DESBANEO, CHAT_CERRADO, INCIDENCIA, QUEJA, MEJORA, ERROR_APP, SUGERENCIA, OTRO");
        }
    }

    private ZoneId resolveZoneId(String tz) {
        if (tz == null || tz.isBlank()) {
            return ZoneId.systemDefault();
        }
        try {
            return ZoneId.of(tz.trim());
        } catch (Exception ex) {
            throw new IllegalArgumentException("tz invalida: " + tz);
        }
    }

    private String normalizeOptionalReason(String reasonRaw, String fieldName) {
        return normalizeOptionalReason(reasonRaw, fieldName, MAX_REASON_LENGTH);
    }

    private String normalizeOptionalReason(String reasonRaw, String fieldName, int maxLength) {
        if (reasonRaw == null) {
            return null;
        }
        if (reasonRaw.indexOf('\u0000') >= 0) {
            throw new IllegalArgumentException(fieldName + " contiene null bytes no permitidos");
        }
        String normalized = reasonRaw.replaceAll("[\\p{Cntrl}&&[^\\r\\n\\t]]", " ").trim();
        if (normalized.isEmpty()) {
            return null;
        }
        if (normalized.length() > maxLength) {
            throw new IllegalArgumentException(fieldName + " supera el maximo de " + maxLength + " caracteres");
        }
        return normalized;
    }

    private String trimToNullable(String value, int maxLen) {
        if (value == null) {
            return null;
        }
        String out = value.trim();
        if (out.isEmpty()) {
            return null;
        }
        return out.length() <= maxLen ? out : out.substring(0, maxLen);
    }

    private String safeAuditValue(String value) {
        if (value == null || value.isBlank()) {
            return "-";
        }
        String trimmed = value.trim();
        return trimmed.length() <= 256 ? trimmed : trimmed.substring(0, 256);
    }

    private String resolveRequestIp(HttpServletRequest request) {
        if (request == null) {
            return "-";
        }
        String forwarded = request.getHeader("X-Forwarded-For");
        if (forwarded != null && !forwarded.isBlank()) {
            return forwarded.split(",")[0].trim();
        }
        String realIp = request.getHeader("X-Real-IP");
        if (realIp != null && !realIp.isBlank()) {
            return realIp.trim();
        }
        String remoteAddr = request.getRemoteAddr();
        return remoteAddr == null || remoteAddr.isBlank() ? "-" : remoteAddr.trim();
    }

    private String resolveRequestUserAgent(HttpServletRequest request) {
        if (request == null) {
            return "-";
        }
        String userAgent = request.getHeader("User-Agent");
        return userAgent == null || userAgent.isBlank() ? "-" : userAgent.trim();
    }

    private String safeEmailValue(String value) {
        if (value == null) {
            return "";
        }
        return value.replaceAll("[\\p{Cntrl}&&[^\\r\\n\\t]]", " ").trim();
    }

    private String defaultString(String value, String fallback) {
        return value == null || value.isBlank() ? fallback : value.trim();
    }

    private void registrarHistorialCreacion(SolicitudDesbaneoEntity entity) {
        try {
            SolicitudReporteHistorialEntity historial = new SolicitudReporteHistorialEntity();
            historial.setSolicitudId(entity.getId());
            historial.setTipoReporte(entity.getTipoReporte());
            historial.setEstadoAnterior(null);
            historial.setEstadoNuevo(entity.getEstado());
            historial.setMotivoSnapshot(trimToNullable(entity.getMotivo(), MAX_REASON_LENGTH));
            historial.setResolucionMotivo(trimToNullable(entity.getResolucionMotivo(), MAX_REASON_LENGTH));
            historial.setUsuarioId(entity.getUsuarioId());
            historial.setAdminId(entity.getReviewedByAdminId());
            historial.setAccion(ACTION_CREACION);
            historial.setCreatedAt(entity.getCreatedAt());
            solicitudReporteHistorialRepository.save(historial);
            LOGGER.info("[ADMIN][REPORT_HISTORY] solicitudId={} action=CREACION estadoNuevo={} created=true",
                    entity.getId(), entity.getEstado());
        } catch (RuntimeException ex) {
            LOGGER.warn("[ADMIN][REPORT_HISTORY] solicitudId={} created=false error={}",
                    entity == null ? null : entity.getId(), safeAuditValue(ex.getMessage()));
        }
    }

    private void registrarHistorialCambioEstado(String requestId,
                                                SolicitudDesbaneoEntity entity,
                                                SolicitudDesbaneoEstado estadoAnterior,
                                                SolicitudDesbaneoEstado estadoNuevo,
                                                Long adminId,
                                                String resolucionMotivo) {
        if (entity == null || entity.getId() == null || estadoNuevo == null) {
            return;
        }
        if (estadoAnterior == estadoNuevo) {
            LOGGER.info("[ADMIN][REPORT_HISTORY] requestId={} solicitudId={} action=CAMBIO_ESTADO estadoAnterior={} estadoNuevo={} created=false motivo=same-state",
                    requestId, entity.getId(), estadoAnterior, estadoNuevo);
            return;
        }
        try {
            SolicitudReporteHistorialEntity last = solicitudReporteHistorialRepository.findTopBySolicitudIdOrderByCreatedAtDesc(entity.getId());
            if (last != null
                    && ACTION_CAMBIO_ESTADO.equals(last.getAccion())
                    && last.getEstadoNuevo() == estadoNuevo
                    && Objects.equals(trimToNullable(last.getResolucionMotivo(), MAX_REASON_LENGTH), trimToNullable(resolucionMotivo, MAX_REASON_LENGTH))
                    && Objects.equals(last.getAdminId(), adminId)) {
                LOGGER.info("[ADMIN][REPORT_HISTORY] requestId={} solicitudId={} action=CAMBIO_ESTADO estadoAnterior={} estadoNuevo={} created=false motivo=duplicate-last",
                        requestId, entity.getId(), estadoAnterior, estadoNuevo);
                return;
            }

            SolicitudReporteHistorialEntity historial = new SolicitudReporteHistorialEntity();
            historial.setSolicitudId(entity.getId());
            historial.setTipoReporte(entity.getTipoReporte());
            historial.setEstadoAnterior(estadoAnterior);
            historial.setEstadoNuevo(estadoNuevo);
            historial.setMotivoSnapshot(trimToNullable(entity.getMotivo(), MAX_REASON_LENGTH));
            historial.setResolucionMotivo(trimToNullable(resolucionMotivo, MAX_REASON_LENGTH));
            historial.setUsuarioId(entity.getUsuarioId());
            historial.setAdminId(adminId);
            historial.setAccion(ACTION_CAMBIO_ESTADO);
            historial.setCreatedAt(entity.getUpdatedAt() == null ? LocalDateTime.now() : entity.getUpdatedAt());
            SolicitudReporteHistorialEntity saved = solicitudReporteHistorialRepository.save(historial);
            LOGGER.info("[ADMIN][REPORT_HISTORY] requestId={} solicitudId={} action=CAMBIO_ESTADO estadoAnterior={} estadoNuevo={} created=true historialId={}",
                    requestId, entity.getId(), estadoAnterior, estadoNuevo, saved.getId());
        } catch (RuntimeException ex) {
            LOGGER.warn("[ADMIN][REPORT_HISTORY] requestId={} solicitudId={} created=false error={}",
                    requestId, entity.getId(), safeAuditValue(ex.getMessage()));
        }
    }

    private boolean hasText(String value) {
        return value != null && !value.trim().isEmpty();
    }

    private boolean isBlank(String value) {
        return !hasText(value);
    }

    private String buildChatReopenSubject(boolean approved, String chatNameSnapshot) {
        String group = defaultString(chatNameSnapshot, "grupo");
        return approved
                ? "Reapertura de chat aprobada: " + group
                : "Reapertura de chat rechazada: " + group;
    }

    private List<SolicitudDesbaneoEstado> parseEstadosFilter(String estadoLegacy, String estadosCsv) {
        String source = (estadosCsv != null && !estadosCsv.isBlank()) ? estadosCsv : estadoLegacy;
        if (source == null || source.isBlank()) {
            return List.of();
        }

        LinkedHashSet<SolicitudDesbaneoEstado> parsed = new LinkedHashSet<>();
        String[] tokens = source.split(",");
        for (String token : tokens) {
            if (token == null || token.isBlank()) {
                continue;
            }
            parsed.add(parseEstadoRequired(token));
        }
        return new ArrayList<>(parsed);
    }

    private SolicitudDesbaneoEstado parseEstadoRequired(String raw) {
        try {
            return SolicitudDesbaneoEstado.valueOf(raw.trim().toUpperCase(Locale.ROOT));
        } catch (IllegalArgumentException ex) {
            throw new IllegalArgumentException("estado invalido. Valores permitidos: PENDIENTE, EN_REVISION, APROBADA, RECHAZADA");
        }
    }
}
